name: Container Image Builds

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: ["v*"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  images:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Find reference version
        uses: greenbone/actions/reference-version@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v1
      - name: Build wheel
        run: poetry build -f wheel
      - name: Build and push Container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }}
          file: .docker/pheme.Dockerfile